### ISSUE TITLE
有没有计划添加多语言版本？

### ISSUE THREAD

**Issue by limbo0312** [aaPanel/BaoTa#12]
最近把bt.cn推荐给一个老外朋友。那家伙对宝塔极有好感，相比其他服务器面板，宝塔做得更为贴心。可惜就是宝塔没有英文版本，否则他就能推荐给更多朋友了。

**Comment by showpy** [comment]
宝塔有英文版，https://www.aapanel.com/

**Comment by limbo0312** [comment]
感谢。宝塔非常好用

**Comment by limbo0312** [comment]
https://forum.aapanel.com/tags   请问这个论坛用了那个开源工具呢
