### ISSUE TITLE
BUG反馈: 数据库管理中 添加数据库和用户,没有赋予权限

### ISSUE THREAD

**Issue by pch18** [aaPanel/BaoTa#22]
在面板中添加数据库和用户时.
如果数据库名称包含  ` . `  则创建的账号没有赋予操作该数据库的权限.
如果数据库名不包含 ` . ` 创建的账号包含 ` . ` 则不影响

数据库命名规则没有说不可以使用 ` . ` 
而且在`phpmyadmin`中是可以正常操作并赋予数据库名包含 ` . ` 的数据库的

猜测问题赋予权限时没有转义数据库名称中的特殊字符.
希望尽快解决此问题.每次创建数据库后还要去`phpmyadmin`中赋予权限,很麻烦.

**Comment by aaPanel** [comment]
您好，确实是分配权限时没有针对特殊符号进行处理，已经修复并更新到云端，请在首页修复面板即可
