### ISSUE TITLE
建议删除bt-uninstall.sh

### ISSUE THREAD

**Issue by NameLessKnight** [aaPanel/BaoTa#27]
http://download.bt.cn/install/bt-uninstall.sh
这个脚本我看挺多blog写着，但都不说会卸载gitlab，还删除仓库
官方文档里最好说明下
或者把gitlab的部分移除

**Comment by goofeng** [comment]
同意

**Comment by jjhesk** [comment]
there is no gitlab installation. @NameLessKnight

**Comment by kaho954** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
