### ISSUE TITLE
CentOS中使用命令更改面板端口不会触发自动更改防火墙放行端口

### ISSUE THREAD

**Issue by mlgexyz** [aaPanel/BaoTa#4]
如题，执行命令行`echo '12580' > /www/server/panel/data/port.pl && /etc/init.d/bt restart`后，面板端口已经从8888改为12580，但firewalld中放行的依旧是8888，必须要手动放行12580才能正常访问面板。

**Comment by aaPanel** [comment]
您好，使用bt命令或在面板中修改端口才会被加入防火墙放行。

**Comment by mlgexyz** [comment]
如果bt命令是指[这个](https://www.bt.cn/btcode.html)的话，那我用的是bt命令没错。
![图片](https://user-images.githubusercontent.com/21287731/59615597-5c66cf00-9155-11e9-8ff2-ce8e55323747.png)

**Comment by showpy** [comment]
直接在命令行输入bt命令，
如果你非要用这条命令的话，你还得往下看有关防火墙放行的说明
