### ISSUE TITLE
安全漏洞

### ISSUE THREAD

**Issue by haby0** [aaPanel/BaoTa#83]
报告安全漏洞的正确联系人是谁？谢谢！

**Comment by haby0** [comment]
Security Vulnerability.

What would be the right contact to report a security vulnerabilty? thanks!

**Comment by Liang2580** [comment]
联系mail 1249648969@qq.com

**Comment by Liang2580** [comment]
参考；https://github.com/aaPanel/aaPanel/blob/master/SECURITY.md

**Comment by Liang2580** [comment]
参考；https://github.com/aaPanel/aaPanel/blob/master/SECURITY.md

**Comment by haby0** [comment]
> 联系mail [1249648969@qq.com](mailto:1249648969@qq.com)

谢谢
